

def helper():
    try:
        pass
    except Exception:
        raise Exception('error: fail to do something')
